
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package kr.pe.constr.webservice.consumer.stub;

import java.util.logging.Logger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.logging.log4j.LogManager;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-05-28T16:58:19.243+09:00
 * Generated source version: 3.0.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "RndProviderImplService",
                      portName = "RndProviderImplPort",
                      targetNamespace = "http://webservice.constr.pe.kr/",
                      wsdlLocation = "http://localhost:9080/webservice/RndProvider?wsdl",
                      endpointInterface = "kr.pe.constr.webservice.consumer.stub.RndProvider")
                      
public class RndProviderImplPortImpl implements RndProvider {

    private static final Logger LOG = Logger.getLogger(RndProviderImplPortImpl.class.getName());
   /* (non-Javadoc)
     * @see kr.pe.constr.webservice.consumer.stub.RndProvider#acet(kr.pe.constr.webservice.consumer.stub.UserVo  arg0 )*
     */
    public int acet(kr.pe.constr.webservice.consumer.stub.UserVo arg0) { 
        LOG.info("Executing operation acet");
        System.out.println(arg0);
        try {
            int _return = -1831381413;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
