
package kr.pe.constr.webservice.consumer.stub;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-05-28T16:58:19.199+09:00
 * Generated source version: 3.0.0
 * 
 */
public final class RndProvider_RndProviderImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.constr.pe.kr/", "RndProviderImplService");

    private RndProvider_RndProviderImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RndProviderImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RndProviderImplService ss = new RndProviderImplService(wsdlURL, SERVICE_NAME);
        RndProvider port = ss.getRndProviderImplPort();  
        
        {
        System.out.println("Invoking acet...");
        kr.pe.constr.webservice.consumer.stub.UserVo _acet_arg0 = new kr.pe.constr.webservice.consumer.stub.UserVo();
        _acet_arg0.setId("Id728769389");
        _acet_arg0.setName("Name1342192952");
        int _acet__return = port.acet(_acet_arg0);
        System.out.println("acet.result=" + _acet__return);


        }

        System.exit(0);
    }

}
