package kr.pe.constr.webservice.consumer.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-05-28T16:58:19.257+09:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://webservice.constr.pe.kr/", name = "RndProvider")
@XmlSeeAlso({ObjectFactory.class})
public interface RndProvider {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "acet", targetNamespace = "http://webservice.constr.pe.kr/", className = "kr.pe.constr.webservice.consumer.stub.Acet")
    @WebMethod
    @ResponseWrapper(localName = "acetResponse", targetNamespace = "http://webservice.constr.pe.kr/", className = "kr.pe.constr.webservice.consumer.stub.AcetResponse")
    public int acet(
        @WebParam(name = "arg0", targetNamespace = "")
        kr.pe.constr.webservice.consumer.stub.UserVo arg0
    );
}
